### ISSUE TITLE
"You can contact me"

### ISSUE THREAD

**Issue by NotSoMik** [Nathaniel-VFX/Discord.js-v14-Command-Handlers#1]
Well maybe if you accept the friend requests someone can contact you

**Comment by Nathaniel-VFX** [comment]
> Well maybe if you accept the friend requests someone can contact you

Hmm... Can you send the friend request again pls?

**Comment by Nathaniel-VFX** [comment]
Send me friend request again on Discord if you need any help. I have updated the code since I found out some problems.
