### ISSUE TITLE
buttonInteraction.js:7:32

### ISSUE THREAD

**Issue by FisbanRegner** [Nathaniel-VFX/Discord.js-v14-Command-Handlers#18]
TypeError: Cannot read properties of undefined (reading 'get')
`const button = client.buttons.get(interaction.customId);`
is throwing an error every time a button is pushed even if the button doesn't belong to the current bot

**Comment by Nathaniel-VFX** [comment]
Remember to define `client.buttons` in index.js
`client.buttons = new Collection()`
