### ISSUE TITLE
example button response

### ISSUE THREAD

**Issue by KayrozDbs** [Nathaniel-VFX/Discord.js-v14-Command-Handlers#5]
Hello , i need to create response with button in embed , if u can send example command it's very nice ^^

**Comment by Nathaniel-VFX** [comment]
Hello, I just added an example of creating button with embed. I used the message component collector and it will response a message and disable buttons + change color when a button is pressed. You may check it out:
https://github.com/Nathaniel-VFX/Discord.js-v14-Command-Handlers/blob/main/slashCommands/fun/color.js
