### ISSUE TITLE
I could use some help here

### ISSUE THREAD

**Issue by FisbanRegner** [Nathaniel-VFX/Discord.js-v14-Command-Handlers#8]
I'm looking to use this in my bot but I'm having troubles using it with a command that requires arguments and options could you please add an example command that takes an argument and uses it as part of the command. A simple get user info or a say hello to user command would do, as this would give me a base on how to use the argument with your code

**Comment by D99-1** [comment]
```const { EmbedBuilder } = require("discord.js");
module.exports = {
    name: "prefix",
    description: "Set the prefix for the guild.",
    usage: "prefix [new prefix]",
    userPerms: ['Administrator'],
    owner: false,
  run: async (client, message, args, prefix, config, db) => {
    if (!args[0]) return message.reply({ embeds: [
      new EmbedBuilder()
        .setTitle("Missing argument")
        .setDescription("Please provide a new prefix!")
    ]});
```
Specify args in your run: async() and then use as required 
Eg. If command was `!prefix .. abc` then args[0] would be `..` and args[1] would be `abc`

**Comment by FisbanRegner** [comment]
Thank you
And 
FYI I think somebody ripped this off the code is exactly the same except they use 🟢 instead of ✅️ they did say it was based off this code but I couldn't see any difference

**Comment by D99-1** [comment]
@FisbanRegner it's fine as long as they gave credit to @Nathaniel-VFX
